SP-771 - add deploy and workspace destroy

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,10 +16,6 @@ jobs:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
       - uses: unfor19/install-aws-cli-action@v1
-
-      - name: Code Artifact login
-        run: |
-          ./login_code_artifact.sh -a 288342028542 -t pip
       - name: Install requirements
         working-directory: ./docs/ci_scripts
         run: |
@@ -76,6 +72,15 @@ jobs:
       - name: unzip
         run: |
           unzip ./opg-data-lpa.zip -d .
+
+      - name: Configure AWS Credentials For Terraform
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-1
+          role-session-name: GitHubActionsTerraform
+          
       - uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 0.14.11
@@ -102,44 +107,88 @@ jobs:
         run: |
           terraform plan -input=false
   
-  pact_verification:
-    runs-on: ubuntu-latest
-    needs: terraform_checks
-    env:
-      # GIT_CONSUMER: << pipeline.parameters.consumer >>
-      # GIT_COMMIT_CONSUMER: << pipeline.parameters.consumerversion >>
-      PACT_PROVIDER: lpa
-      PACT_CONSUMER: sirius
-      PACT_BROKER_BASE_URL: https://pact-broker.api.opg.service.justice.gov.uk
-      PACT_BROKER_HTTP_AUTH_USER: admin
+  # pact_verification:
+  #   runs-on: ubuntu-latest
+  #   needs: terraform_checks
+  #   env:
+  #     # GIT_CONSUMER: << pipeline.parameters.consumer >>
+  #     # GIT_COMMIT_CONSUMER: << pipeline.parameters.consumerversion >>
+  #     PACT_PROVIDER: lpa
+  #     PACT_CONSUMER: sirius
+  #     PACT_BROKER_BASE_URL: https://pact-broker.api.opg.service.justice.gov.uk
+  #     PACT_BROKER_HTTP_AUTH_USER: admin
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Pact Install
+  #       run: |
+  #         wget https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.82.3/pact-1.82.3-linux-x86_64.tar.gz
+  #         tar xzf pact-1.82.3-linux-x86_64.tar.gz
+  #     - name: Code artifact login
+  #       working-directory: ./docs/ci_scripts
+  #       run: |
+  #         ./login_code_artifact.sh -a 288342028542 -t pip
+
+  #     - name: install ci requirements
+  #       working-directory: ./pact
+  #       run: | 
+  #         pip3 install -r requirements.txt
+          
+  #     - name: verify pact
+  #       working-directory: ./pact
+  #       run: |
+  #         echo ${API_VERSION}
+  #         python check_pact_deployable.py \
+  #         --provider_base_url="http://localhost:4343" \
+  #         --pact_broker_url="${PACT_BROKER_BASE_URL}" \
+  #         --broker_user_name="admin" \
+  #         --broker_secret_name="pactbroker_admin" \
+  #         --consumer_pacticipant="${PACT_CONSUMER}" \
+  #         --provider_pacticipant="${PACT_PROVIDER}" \
+  #         --api_version="${API_VERSION}" \
+  #         --git_commit_consumer="${GIT_COMMIT_CONSUMER}" \
+  #         --git_commit_provider="${GIT_COMMIT_PROVIDER}" || echo "Failed but because consumer pacts not set up yet"
+
+  ephemeral_environment:
+    name: Create Ephemeral Environment
+    runs-on: "ubuntu-latest"
+    needs: [build_and_test, terraform_checks]
     steps:
       - uses: actions/checkout@v2
-      - name: Pact Install
+      - uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.0.0
+      - name: Extract branch name
+        shell: bash
+        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
+        id: extract_branch
+      - name: Install workspace manager
         run: |
-          wget https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.82.3/pact-1.82.3-linux-x86_64.tar.gz
-          tar xzf pact-1.82.3-linux-x86_64.tar.gz
-      - name: Code artifact login
-        working-directory: ./docs/ci_scripts
+          wget https://github.com/TomTucka/terraform-workspace-manager/releases/download/v0.3.0/terraform-workspace-manager_Linux_x86_64.tar.gz -O $HOME/terraform-workspace-manager.tar.gz
+          sudo tar -xvf $HOME/terraform-workspace-manager.tar.gz -C /usr/local/bin
+          sudo chmod +x /usr/local/bin/terraform-workspace-manager
+      - name: Configure AWS Credentials For Terraform
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-1
+          role-session-name: GitHubActionsTerraform
+      - name: Download Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: opg-data-lpa
+      - name: Unzip Artifact
+        run: unzip ./opg-data-lpa-codes.zip -d .
+      - name: Setup Workspace
+        run: echo TF_WORKSPACE= ${{ steps.extract_branch.outputs.branch }}
+      - name: Terraform init
+        working-directory: ./terraform/environment
         run: |
-          ./login_code_artifact.sh -a 288342028542 -t pip
-
-      - name: install ci requirements
-        working-directory: ./pact
-        run: | 
-          pip3 install -r requirements.txt
-          
-      - name: verify pact
-        working-directory: ./pact
+          terraform init
+      - name: Terraform apply
+        working-directory: ./terraform/environment
         run: |
-          echo ${API_VERSION}
-          python check_pact_deployable.py \
-          --provider_base_url="http://localhost:4343" \
-          --pact_broker_url="${PACT_BROKER_BASE_URL}" \
-          --broker_user_name="admin" \
-          --broker_secret_name="pactbroker_admin" \
-          --consumer_pacticipant="${PACT_CONSUMER}" \
-          --provider_pacticipant="${PACT_PROVIDER}" \
-          --api_version="${API_VERSION}" \
-          --git_commit_consumer="${GIT_COMMIT_CONSUMER}" \
-          --git_commit_provider="${GIT_COMMIT_PROVIDER}" || echo "Failed but because consumer pacts not set up yet"
+          terraform apply --auto-approve
+      - name: Protect Workspace
+        run: terraform-workspace-manager -register-workspace=$TF_WORKSPACE -time-to-protect=1 -aws-account-id=288342028542 -aws-iam-role=integrations-ci
          
